---
platform: linux

inputs:
  - name: repo           # Repository containing task scripts and CLI tool
  - name: config-repo    # Configuration repository
  - name: cli-tool-bin   # Directory containing the CLI tool binaries
  - name: pks-config     # PKS/TKGi configuration from previous task

run:
  path: repo/ci/tasks/cli-tool/configure-tool/task.sh

params:
  # Required parameters
  FOUNDATION: ((foundation))              # Foundation name (e.g., cml-k8s-n-01)
  TOOL_NAME: ((tool_name))                # Name of the CLI tool (e.g., tridentctl)
  
  # Optional parameters
  NAMESPACE: ((namespace))                # Namespace to configure
  CONFIG_PATH: ((config_path))            # Path to configuration files
  CONFIG_OPTIONS: ((config_options))      # Additional configuration options
  VERBOSE: ((verbose))                    # Enable verbose output