# Template Generator Configuration
# This is a sample configuration file for the generate-reference-template.py script

# Organization and repository information
org_name: "Utilities-tkgieng"
repo_name: "my-service"

# Git branch configuration
default_branch: "develop"
release_branch: "release"

# Environment configuration
default_environment: "lab"
default_foundation: "cml-k8s-n-01"
default_pipeline: "main"
default_timer_duration: "3h"

# GitHub settings
github_domain: "github.com"

# Additional environment variables to set in generated scripts
env_variables:
  TEST_MODE: "false"
  DEBUG: "false"
  VERBOSE: "false"

# Custom variables - these will be available as ${variable_name} in templates
pipeline_prefix: "svc" # e.g. pipeline will be named svc-main-{foundation}
foundation: "cml-k8s-n-01"
custom_validation_command: "yamllint"