---
platform: linux

inputs:
  - name: repo           # Repository containing task scripts and CLI tool

outputs:
  - name: cli-tool-bin   # Output directory for the CLI tool binaries

run:
  path: repo/ci/tasks/cli-tool/download-tool/task.sh

params:
  # Required parameters
  TOOL_NAME: ((tool_name))                  # Name of the CLI tool (e.g., tridentctl)
  TOOL_VERSION: ((tool_version))            # Version of the CLI tool to download
  
  # Optional parameters
  DOWNLOAD_URL: ((tool_download_url))       # URL to download the tool (if not using built-in logic)
  HARBOR_HOSTNAME: ((harbor_hostname))      # Harbor registry hostname (for container images)
  VERBOSE: ((verbose))                      # Enable verbose output