---
platform: linux

inputs:
  - name: repo           # Repository containing task scripts
  - name: pks-config     # PKS/TKGi configuration
  - name: manifests      # Kubernetes manifests to apply

run:
  path: repo/ci/tasks/common/kubectl-apply/task.sh

params:
  # Required parameters
  FOUNDATION: ((foundation))              # Foundation name (e.g., cml-k8s-n-01)
  PKS_PASSWORD: ((pks_api_admin_pw))      # PKS/TKGi password
  
  # Optional parameters
  KINDS: ((kinds))                        # Comma-separated list of kinds to apply (default: all)
  NAMESPACE_LIMIT: ((namespace_limit))    # Number of namespaces to process (default: 0 = all)
  VERBOSE: ((verbose))                    # Enable verbose output